name: Compress avatar textures

on:
  push:
    paths:
      - textures/** # `textures/`配下にあるファイル（テクスチャ画像）が変更されたらワークフローがトリガーされる。
      - .github/workflows/compress_textures.yml

jobs:
  compress_textures:
    name: Compress avatar textures
    permissions:
      contents: write
    uses: Gakuto1112/FiguraAvatarTextureCompressor/.github/workflows/compress_avatar_texture.yml@main
    with:
      target_branch: ${{ github.ref_name }} # 圧縮処理を行う対象のブランチ名。省略した場合、レポジトリのデフォルトブランチが対象となる。
      # textures_path: textures/ # アバターのテクスチャが格納されたディレクトリ。デフォルトは`textures/`。
      # models_path: models/ # アバターのモデルが格納されたディレクトリ。デフォルトは`models/`。
